"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](iris)\
$os\
$username\
[](bg:lightblue fg:iris)\
$directory\
[](fg:lightblue bg:overlay)\
$time\
[ ](fg:overlay)\
$line_break$character"""

palette = 'futuristic'

[palettes.futuristic]
base = '#191724'
lightblue = '#5994ce'
mediumblue = '#5c58b6'
darkblue = '#3a4e93'
iris = '#c76ce0'
gold = '#ebce5f'
redalert = '#c73530'
highlight = '#b957ce'
highlightLow = '#21202e'
highlightMed = '#403d52'
hightlightHigh = '#524f67'
text = '#e0def4'
surface = '#1f1d2e'
overlay = '#26233e'
muted = '#6e6a86'
subtle = '#908caa'

[os]
disabled = false
style = "bg:iris fg:gold"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:iris fg:overlay"
style_root = "bg:redalert fg:overlay"
format = '[ $user ]($style)'

[directory]
style = "fg:text bg:lightblue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[time]
disabled = false
time_format = "%R"
style = "bg:gold"
format = '[[  $time ](fg:text bg:overlay)]($style)'

[line_break]
disabled = false

[character]
disabled = true
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:gold)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
